apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-box
  namespace: music-app
  labels:
    app: music-box
spec:
  replicas: 1
  template:
    metadata:
      name: music-box
      labels:
        app: music-box
    spec:
      nodeSelector:
        ram: high
      containers:
        - name: music-box
          image: ghcr.io/whoant/music-box:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                { name: secret.music-box }
      restartPolicy: Always
  selector:
    matchLabels:
      app: music-box
