apiVersion: v1
kind: Service
metadata:
  name: music-box
  namespace: music-app
spec:
  selector:
    app: music-box
  ports:
    - port: 8000
      targetPort: 8001
      nodePort: 30013
  type: NodePort
